# testbench
fir1_test.v

# netlist generated by Design Compiler
../syn/netlist/fir1_syn.v

# Logic Gate models
-v /usr/cadtool/GPDK45/gsclib045_svt_v4.4/gsclib045/verilog/slow_vdd1v2_basicCells.v

+define+SDF
