// Autogenerated from Softmax_table.xlsx
module exp_lut (
    input  wire [9:0] lut_idx,
    output reg  [33:0] exp_val
);

// synthesis result, area 11323, timing < 3ns

always @* begin
    case (lut_idx)
        10'd   0: exp_val = 34'h000100000;
        10'd  16: exp_val = 34'h000148b5e;
        10'd  32: exp_val = 34'h0001a6129;
        10'd  48: exp_val = 34'h00021df3b;
        10'd  64: exp_val = 34'h0002b7e15;
        10'd  80: exp_val = 34'h00037d871;
        10'd  96: exp_val = 34'h00047b4ff;
        10'd 112: exp_val = 34'h0005c12da;
        10'd 128: exp_val = 34'h000763992;
        10'd 144: exp_val = 34'h00097cdc4;
        10'd 160: exp_val = 34'h000c2eb7e;
        10'd 176: exp_val = 34'h000fa4838;
        10'd 192: exp_val = 34'h001415e5b;
        10'd 208: exp_val = 34'h0019ca53b;
        10'd 224: exp_val = 34'h00211d8e4;
        10'd 240: exp_val = 34'h002a8565a;
        10'd 256: exp_val = 34'h003699205;
        10'd 272: exp_val = 34'h00461afc4;
        10'd 288: exp_val = 34'h005a0462b;
        10'd 304: exp_val = 34'h00739593a;
        10'd 320: exp_val = 34'h009469c4c;
        10'd 336: exp_val = 34'h00be90f6f;
        10'd 352: exp_val = 34'h00f4b1227;
        10'd 368: exp_val = 34'h013a30cf1;
        10'd 384: exp_val = 34'h01936dc56;
        10'd 400: exp_val = 34'h020603487;
        10'd 416: exp_val = 34'h029924421;
        10'd 432: exp_val = 34'h03560f0b0;
        10'd 448: exp_val = 34'h0448a216a;
        10'd 464: exp_val = 34'h05801ad75;
        10'd 480: exp_val = 34'h07100adba;
        10'd 496: exp_val = 34'h09119289c;
        10'd 512: exp_val = 34'h00000015f;
        10'd 528: exp_val = 34'h0000001c3;
        10'd 544: exp_val = 34'h000000243;
        10'd 560: exp_val = 34'h0000002e8;
        10'd 576: exp_val = 34'h0000003bc;
        10'd 592: exp_val = 34'h0000004cb;
        10'd 608: exp_val = 34'h000000628;
        10'd 624: exp_val = 34'h0000007e8;
        10'd 640: exp_val = 34'h000000a27;
        10'd 656: exp_val = 34'h000000d09;
        10'd 672: exp_val = 34'h0000010bd;
        10'd 688: exp_val = 34'h00000157e;
        10'd 704: exp_val = 34'h000001b99;
        10'd 720: exp_val = 34'h00000236f;
        10'd 736: exp_val = 34'h000002d80;
        10'd 752: exp_val = 34'h000003a6d;
        10'd 768: exp_val = 34'h000004b05;
        10'd 784: exp_val = 34'h000006054;
        10'd 800: exp_val = 34'h000007bb0;
        10'd 816: exp_val = 34'h000009ed1;
        10'd 832: exp_val = 34'h00000cbed;
        10'd 848: exp_val = 34'h0000105d9;
        10'd 864: exp_val = 34'h000015038;
        10'd 880: exp_val = 34'h00001afb7;
        10'd 896: exp_val = 34'h000022a55;
        10'd 912: exp_val = 34'h00002c7c7;
        10'd 928: exp_val = 34'h0000391f0;
        10'd 944: exp_val = 34'h000049586;
        10'd 960: exp_val = 34'h00005e2d5;
        10'd 976: exp_val = 34'h000078ed0;
        10'd 992: exp_val = 34'h00009b459;
        10'd1008: exp_val = 34'h0000c75f7;
        default: exp_val = 34'd0;
    endcase
end

endmodule
