//==============================================================================
// Hierarchical dofile generated by Conformal LEC
// Version: 20.10-p100 (01-May-2020) (64 bit executable)
//------------------------------------------------------------------------------
// The command 'set module property' sets the instance context for the current
// root module. It is intended only for hierarchical comparison, and should
// not be modified by the user.
//==============================================================================

set system mode setup
// Root modules
// Comparing module 'my_div'
set root module my_div -Golden
set root module my_div -Revised
set module property -instance / -Golden
set module property -instance / -Revised
report black box -NOHidden
set system mode lec
analyze setup -verbose;                      analyze multiplier -cdp_info;                      analyze datapath -merge -share -effort medium -verbose;
add compared points -all
compare
analyze abort -compare
save hier_compare result
set system mode setup
report hier_compare result
report hier_compare result -Non_equivalent
report hier_compare result -Abort
report hier_compare result -Uncompared
// _END_OF_LEC_HIERARCHICAL_DOFILE_
